name: El blog <i>del Partido Digital</i>
description: Transparencia y m치s participaci칩n. Una entrada a la vez.
meta_description: "El blog del Partido Digital. Transparencia y m치s participaci칩n."
title: El blog del Partido Digital

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: http://leog.me/kasper/
domain_name: 'http://leog.me/kasper/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://leog.me/kasper/'
author:         'Leonardo Giovanetti'
